version: "3"
volumes:
  mongodb-dev:
    external: true

services:
  api:
    image: node:10.16.3
    working_dir: /app
    volumes:
      - ./app/:/app/
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - MONGO=mongodb://mongo:27017/anakod
    depends_on:
      - mongo
    restart: always
    command: ["bash","-c","npm install && npm run dev"]
  mongo:
    image: mongo
    volumes:
      - mongodb-dev:/data/db
    ports:
      - "30001:27017"
    restart: always
